In [ ]:
# %load miniflow.py
import numpy as np

class Node(object):

    def __init__(self, inbound_nodes=[]):
        
        self.inbound_nodes = inbound_nodes

        self.outbound_nodes = []

        for n in self.inbound_nodes:
            n.outbound_nodes.append(self)

        self.value = None

    def forward(self):
        raise NotImplemented

class Input(Node):

    def __init__(self):
        Node.__init__(self)

    def forward(self, value=None):
        
        if value is not None:
            self.value = value

class Add(Node):

    def __init__(self, x, y):
        Node.__init__(self, [x, y])

    def forward(self):
        self.value = 0
        for i in range(len(self.inbound_nodes)):
            self.value += self.inbound_nodes[i].value
        return self.value 

class Sigmoid(Node):

    def __init__(self, n):
        Node.__init__(self, [n])

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward(self):
        self.value = self._sigmoid(self.inbound_nodes[0].value) 
        return self.value
    
class Linear(Node):

    def __init__(self, inputs, weights, bias):
        Node.__init__(self, [inputs, weights, bias])

    def forward(self):
        inputs = self.inbound_nodes[0].value
        weights = self.inbound_nodes[1].value
        bias = self.inbound_nodes[2].value
        self.value = sum(map(lambda x,y:x*y, inputs,weights)) + bias 
        return self.value
    
class LinearMatrix(Node):

    def __init__(self, X, W, B):
        Node.__init__(self, [X, W, B])

    def forward(self):

        X = self.inbound_nodes[0].value
        W = self.inbound_nodes[1].value
        B = self.inbound_nodes[2].value

        self.value = X.dot(W) + B 
        return self.value

class MSE(Node):

    def __init__(self, y, a):
        Node.__init__(self, [y, a])

    def forward(self):

        y = self.inbound_nodes[0].value.reshape(-1,1)
        a = self.inbound_nodes[1].value.reshape(-1,1)

        #self.value =  sum(np.square(y - a)) / len(y)
        self.value = np.mean(np.square(y - a))

'''
Kahn's algorihtm
'''
def topological_sort(feed_dict):
    
    input_nodes = [n for n in feed_dict.keys()]

    G = {}
    nodes = [n for n in input_nodes]
    while len(nodes) > 0:
        n = nodes.pop(0)
        G.setdefault(n, {'in':set(), 'out': set()})

        for it in n.outbound_nodes:
            G.setdefault(it, {'in':set(), 'out':set()})
            G[n]['out'].add(it)
            G[it]['in'].add(n)

            nodes.append(it)

    L = []
    S = set(input_nodes)
    while (len(S) > 0):
        n = S.pop()

        if isinstance(n, Input):
            n.value = feed_dict[n]

        L.append(n)
        for m in n.outbound_nodes:
            G[n]['out'].remove(m)
            G[m]['in'].remove(n)
            if  len(G[m]['in']) == 0:
                S.add(m)
    #if G:
        #raise RuntimeError("graph has at least one cycle")
        
    return L

def forward_pass(output_node, sorted_nodes):

    for n in sorted_nodes:
        n.forward()

    return output_node.value

def forward_pass_no_ret(sorted_nodes):

    for n in sorted_nodes:
        n.forward()



In [ ]:
%run miniflow.py

x, y = Input(), Input()

f = Add(x, y)

feed_dict = {x:10, y:5}

sorted_nodes = topological_sort(feed_dict)
output = forward_pass(f, sorted_nodes)
print("{} + {} = {} (according to miniflow)".format(feed_dict[x], feed_dict[y], output))


In [22]:
%run miniflow.py


import numpy as np


X, W, b = Input(), Input(), Input()

f = LinearMatrix(X, W, b)

X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2., -3], [2., -3]])
b_ = np.array([-3., -5])

feed_dict = {X: X_, W: W_, b: b_}

graph = topological_sort(feed_dict)
output = forward_pass(f, graph)

"""
Output should be:
[[-9., 4.],
[-9., 4.]]
"""
print(output)

[[-9.  4.]
 [-9.  4.]]


In [32]:
%run miniflow.py

import numpy as np


X, W, b = Input(), Input(), Input()

f = LinearMatrix(X, W, b)
g = Sigmoid(f)

X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2., -3], [2., -3]])
b_ = np.array([-3., -5])

feed_dict = {X: X_, W: W_, b: b_}

graph = topological_sort(feed_dict)
output = forward_pass(g, graph)

"""
Output should be:
[[  1.23394576e-04   9.82013790e-01]
 [  1.23394576e-04   9.82013790e-01]]
"""
print(output)

[[  1.23394576e-04   9.82013790e-01]
 [  1.23394576e-04   9.82013790e-01]]


In [38]:
%run miniflow.py
import numpy as np


y, a = Input(), Input()
cost = MSE(y, a)

y_ = np.array([1, 2, 3])
a_ = np.array([4.5, 5, 10])

feed_dict = {y: y_, a: a_}
graph = topological_sort(feed_dict)
# forward pass
forward_pass_no_ret(graph)

"""
Expected output

23.4166666667
"""
print(cost.value)

23.4166666667


In [48]:
%run f.py

EPOCH 0: Cost=31764501.000, x=11272.000
EPOCH 1: Cost=20329282.440, x=9017.600
EPOCH 2: Cost=13010742.562, x=7214.080
EPOCH 3: Cost=8326877.039, x=5771.264
EPOCH 4: Cost=5329203.105, x=4617.011
EPOCH 5: Cost=3410691.787, x=3693.609
EPOCH 6: Cost=2182844.544, x=2954.887
EPOCH 7: Cost=1397022.308, x=2363.910
EPOCH 8: Cost=894096.077, x=1891.128
EPOCH 9: Cost=572223.289, x=1512.902
EPOCH 10: Cost=366224.705, x=1210.322
EPOCH 11: Cost=234385.611, x=968.257
EPOCH 12: Cost=150008.591, x=774.606
EPOCH 13: Cost=96007.298, x=619.685
EPOCH 14: Cost=61446.471, x=495.748
EPOCH 15: Cost=39327.541, x=396.598
EPOCH 16: Cost=25171.427, x=317.279
EPOCH 17: Cost=16111.513, x=253.823
EPOCH 18: Cost=10313.168, x=203.058
EPOCH 19: Cost=6602.228, x=162.447
EPOCH 20: Cost=4227.226, x=129.957
EPOCH 21: Cost=2707.224, x=103.966
EPOCH 22: Cost=1734.424, x=83.173
EPOCH 23: Cost=1111.831, x=66.538
EPOCH 24: Cost=713.372, x=53.231
EPOCH 25: Cost=458.358, x=42.584
EPOCH 26: Cost=295.149, x=34.068
EPOCH 27: Cost=190